---
<% @version = '2019.2.0' %>
driver:
  name: docker
  use_sudo: false
  privileged: true
  username: root
  forward:
    - 80

provisioner:
  name: salt_solo
  sudo: false
  salt_install: bootstrap
  salt_bootstrap_options: -qX git v<%= @version %>
  log_level: debug
  is_file_root: true
  state_top_from_file: true
  require_chef: false
  salt_copy_filter:
    - .bundle
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - README.rst
    - .travis.yml

platforms:
  - name: ubuntu-18.04
    driver_config:
      run_command: /lib/systemd/systemd

suites:
  - name: salt-apache

verifier:
  name: shell
  remote_exec: false
  command: python3 -m pytest -v tests/
