---
<% @version = '2019.2.0' %>
driver:
  name: docker
  use_sudo: false
  hostname: salt-apache
  privileged: true
  username: root
  cap_add:
    - sys_admin
  disable_upstart: false
  use_internal_docker_network: false
  init_environment: pip3 install pytest
  forward:
    - 80

provisioner:
  name: salt_solo
  sudo: false
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
  salt_bootstrap_options: -qXU git v<%= @version %>
  log_level: debug
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - .bundle
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - README.rst
    - .travis.yml

platforms:
  - name: ubuntu-18.04
    driver_config:
      run_command: /lib/systemd/systemd

suites:
  - name: salt-apache
    provisioner:
      state_top_from_file: true

verifier:
  name: shell
  remote_exec: false
  command: python3 -m pytest -v tests/
