language: ruby
services:
  - docker
rvm:
  - ruby
dist: trusty
env:
  matrix:
    - SUITE=ubuntu-18
script:
  - bundle exec kitchen converge $SUITE
  - bundle exec kitchen verify $SUITE
after_script:
  - bundle exec kitchen list $SUITE
  - bundle exec kitchen destroy $SUITE
