language: ruby
services:
  - docker
rvm:
  - ruby
dist: trusty
env:
  matrix:
    - SUITE=ubuntu-18
bundler_args: --without windows
script:
  # Setup for tests
  - bundle exec kitchen create $SUITE -l warn -c 2
  # Provision containers
  - bundle exec kitchen converge $SUITE
after_script:
  - bundle exec kitchen list $SUITE
  - bundle exec kitchen destroy $SUITE
